### ISSUE TITLE
Investigate field_with_errors CSS

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#332]
```css
.field_with_errors {display: inline-block;} /* Keeps forms from whitespacing weirdly when errors present */
```

This seems to make the fields on `characters#edit` function weirdly if there's an error with the field (e.g. name if it's blank and you try to save).
